apiVersion: v1
kind: Service
metadata:
  name: my-nginx-service
  namespace: nginx-dev
spec:
  type: NodePort
  selector:
    app: my-nginx
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
